corpus_id: 2
customer_id: 1558168672
auth_api_key: "zqt_XN_EYOm1x-FH-ky3KXUNHTXsrcNRbpHkXjSy5w"

search_title_pre: "Search demo of Best Writing"
search_title_inner: "Best Writing website"
search_title_post: "content"
search_title_url: "https://bestwriting.com"
Q1: "Technical writing jobs"
Q2: "High-paying writing jobs"
Q3: "Freelance writing jobs for students"
Q4: "Calm companies hiring editors"
